export const GET_SUMMARY = 'GET_SUMMARY'
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS'
export const GET_SUMMARY_ERROR = 'GET_SUMMARY_ERROR'

export const GET_SUMMARY_BY_ID = 'GET_SUMMARY_BY_ID'
export const GET_SUMMARY_BY_ID_SUCCESS = 'GET_SUMMARY_BY_ID_SUCCESS'
export const GET_SUMMARY_BY_ID_ERROR = 'GET_SUMMARY_BY_ID_ERROR'

export const DELETE_SUMMARY = 'DELETE_SUMMARY'
export const DELETE_SUMMARY_SUCCESS = 'DELETE_SUMMARY_SUCCESS'
export const DELETE_SUMMARY_ERROR = 'DELETE_SUMMARY_ERROR'

export const POST_SUMMARY = 'POST_SUMMARY'
export const POST_SUMMARY_ERROR = 'POST_SUMMARY_ERROR'
export const POST_SUMMARY_SUCCESS = 'POST_SUMMARY_SUCCESS'

export const PUT_SUMMARY = 'PUT_SUMMARY'
export const PUT_SUMMARY_ERROR = 'PUT_SUMMARY_ERROR'
export const PUT_SUMMARY_SUCCESS = 'PUT_SUMMARY_SUCCESS'

export const RESET_LOADING = 'RESET_LOADING'
