export const GET_SUMMARY = 'GET_SUMMARY'
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS'
export const GET_SUMMARY_ERROR = 'GET_SUMMARY_ERROR'

export const GET_SUMMARY_BY_ID = 'GET_SUMMARY_BY_ID'
export const GET_SUMMARY_BY_ID_SUCCESS = 'GET_SUMMARY_BY_ID_SUCCESS'
export const GET_SUMMARY_BY_ID_ERROR = 'GET_SUMMARY_BY_ID_ERROR'