export const GET_SUMMARY = 'GET_SUMMARY'
export const GET_SUMMARY_SUCCESS = 'GET_SUMMARY_SUCCESS'
export const GET_SUMMARY_ERROR = 'GET_SUMMARY_ERROR'

export const GET_SUMMARY_BY_ID = 'GET_SUMMARY_BY_ID'
export const GET_SUMMARY_BY_ID_SUCCESS = 'GET_SUMMARY_BY_ID_SUCCESS'
export const GET_SUMMARY_BY_ID_ERROR = 'GET_SUMMARY_BY_ID_ERROR'

export const DELETE_SUMMARY = 'DELETE_SUMMARY'
export const DELETE_SUMMARY_SUCCESS = 'DELETE_SUMMARY_SUCCESS'
export const DELETE_SUMMARY_ERROR = 'DELETE_SUMMARY_ERROR'

export const ADD_TITLE_SUMMARY = 'ADD_TITLE_SUMMARY'
export const ADD_DESCRIPT_SUMMARY = 'ADD_DESCRIPT_SUMMARY'

export const ADD_EDUCATION_TITLE_SUMMARY = 'ADD_EDUCATION_TITLE_SUMMARY'

export const CANCEL_ADD_EDUCATION = 'CANCEL_ADD_EDUCATION'
export const ADD_EDUCATION_LIST = 'ADD_EDUCATION_LIST'
export const YEAR_EDUCATION = 'YEAR_EDUCATION'

export const ADD_TITLE_LANGUAGE = 'ADD_TITLE_LANGUAGE'
export const ADD_DESCRIPT_LANGUAGE = 'ADD_DESCRIPT_LANGUAGE'
export const CANCEL_LANGUAGE = 'CANCEL_LANGUAGE'
export const ADD_LANGUAGE = 'ADD_LANGUAGE'

export const ADD_PHONE = 'ADD_PHONE'
export const ADD_TAGS = 'ADD_TAGS'

export const ADD_HISTORY = 'ADD_HISTORY'
export const DEL_HISTORY = 'DEL_HISTORY'

export const POST_SUMMARY = 'POST_SUMMARY'
export const POST_SUMMARY_ERROR = 'POST_SUMMARY_ERROR'
export const POST_SUMMARY_SUCCESS = 'POST_SUMMARY_SUCCESS'
