export const GET_USER_SUMMARY = 'GET_USER_SUMMARY'
export const GET_USER_SUMMARY_ERROR = 'GET_USER_SUMMARY_ERROR'
export const GET_USER_SUMMARY_SUCCESS = 'GET_USER_SUMMARY_SUCCESS'

export const DELETE_SUMMARY = 'DELETE_SUMMARY'
export const DELETE_SUMMARY_SUCCESS = 'DELETE_SUMMARY_SUCCESS'
export const DELETE_SUMMARY_ERROR = 'DELETE_SUMMARY_ERROR'
